name: CICD Simethris

on:
  push:
    branches: ["master"]

jobs:
  build-master:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:

      - uses: actions/checkout@v3
      - name: Stash local changes (if any)
        run: |
          cd ${{ vars.GIT_WORKDIR_MASTER }}
          git stash || echo "Nothing to stash"
      - name: Pull latest changes
        run: |
          cd ${{ vars.GIT_WORKDIR_MASTER }}
          git pull
      - name: Apply stashed changes (if any)
        run: |
          cd ${{ vars.GIT_WORKDIR_MASTER }}
          git stash pop || echo "No stashed changes to apply"
      - name: Run artisan optimize:clear
        run: |
          cd ${{ vars.GIT_WORKDIR_MASTER }}
          php artisan optimize:clear
          cd ..

 



   


