name: CICD Simethris

on:
  push:
    branches: ["master"]

jobs:
  build-master:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:

      - uses: actions/checkout@v3
      - name: Remove untracked files and directories
        run: |
          cd ${{ vars.GIT_WORKDIR_MASTER }}
          git clean -fd   # Removes only untracked files and directories
      - name: Pull latest changes
        run: |
          cd ${{ vars.GIT_WORKDIR_MASTER }}
          git pull
      
      - name: Run artisan optimize:clear
        run: |
          cd ${{ vars.GIT_WORKDIR_MASTER }}
          php artisan optimize:clear
          cd ..

 



   


